os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
deploy:
  provider: script
  script:
    - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: dm5upeyH+xN3/73l0q/3WcJ+DlD79jzxjmBNh0EN2OADdGPUFkRQ3gBgafEvnifYaYt7o3mdBZkFYg7CYZks6Gv+rIjTzqK+OO/xm8WmiFr1RKcVjphoQ4D+JNuHMzMHYQTiYpLNRhxKwTUxWzrV5jfe8nd2Jv6+nVLQvU9VlBX9I/2WJlXANHjfz/B7Pztjc+JSOboTQHghmKXH0NX1TrR2goJr8w4TqrvCWzSxFTKsocntCPT6onngt0iB4VLwW4S/Eddh13eqXE+HiQ762o6MdtQw7xqhZQCHiceVde3yxCoSS3heOs/4n6Jj51cLhShIVKaHC8dCk7vckARguzt4i2vKja0PFvTT6yEhwnmrbqCG+n1TTxQyRECAm5vODVoAEMjaQuQtm8UDXYQ0nJ1QTqD3PP4lGqKkDGlJ5y0GQrlLdaaXgfvwTCV92LpqexGQhfdcQFQDdzSpQb6e3+L9A/zo5x0egWRKkdiB+fLIQZ7CagE//tyN1K3bBjV0cUxr/Hx4uLu66LK6j5RZSEkn9DdPyLX0HxCCUn9AHyHIFu6TPGlOotZGTegZiGMeOV0JuHBKv9FEy6hhNVceUJ/wwVe3M/3YEByxica04meffBCuBRcq6L6VcpDiypsTtNVp+S+GAThlAgteljij7uMCxfrOaqf6UjyQUPphG7I=